#!/usr/bin/env python3
"""Render the Codex-authored PR attribution sentence from rollout history."""

from __future__ import annotations

import argparse
from collections import Counter, deque
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import time
from typing import (
    BinaryIO,
    Dict,
    Iterable,
    Iterator,
    List,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
)
import uuid


FALLBACK_LABEL = "GPT-5.6 Sol Ultra"
SENTENCE = "This PR is purely generated by LLM: OpenAI Codex ({})."
MAX_RECORD_BYTES = 1024 * 1024
MAX_FILE_BYTES = 512 * 1024 * 1024
MAX_PROBE_BYTES = 1024 * 1024
MAX_ENTRIES = 100_000
MAX_FILES = 50_000
MAX_DEPTH = 8
MAX_INVENTORY_REVALIDATION_ATTEMPTS = 3
MAX_REVALIDATION_ENTRIES = MAX_ENTRIES * MAX_INVENTORY_REVALIDATION_ATTEMPTS
MAX_TURNS = 100_000
MAX_VOTE_COPIES = 200_000
MAX_ID_CHARS = 1024
DEADLINE_SECONDS = 30.0
UUID_RE = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)
MODEL_LABELS = {
    "gpt-5.5": "GPT-5.5",
    "gpt-5.6-sol": "GPT-5.6 Sol",
    "gpt-5.6-terra": "GPT-5.6 Terra",
}
MODEL_ALIASES = {
    "gpt-5.6-sol": "gpt-5.6-sol",
    "gpt-5.6-terra": "gpt-5.6-terra",
    "gpt-5.5": "gpt-5.5",
    "gpt-5.4": "gpt-5.4",
    "gpt-5.3": "gpt-5.3-codex",
    "gpt-5.3-codex": "gpt-5.3-codex",
}
EFFORT_LABELS = {
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "xhigh": "Extra High",
    "max": "Max",
    "ultra": "Ultra",
}
Pair = Tuple[str, str]
TurnKey = Tuple[str, str]
FileIdentity = Tuple[int, int]


class RolloutError(RuntimeError):
    """The selected task family cannot supply complete attribution evidence."""


@dataclass(frozen=True)
class Vote:
    pair: Pair
    turn_order: Optional[int]


@dataclass
class FileSnapshot:
    identity: FileIdentity
    inventory_size: int
    prefix_size: Optional[int] = None
    prefix_sha256: Optional[str] = None


@dataclass(frozen=True)
class CandidateSnapshot:
    identity: FileIdentity
    size: int
    active: bool


@dataclass(frozen=True)
class DirectoryEntrySnapshot:
    name: str
    identity: FileIdentity
    file_type: int


@dataclass(frozen=True)
class InventorySnapshot:
    directories: Mapping[Path, FileIdentity]
    candidates: Mapping[Path, CandidateSnapshot]


def check_deadline(deadline: float) -> None:
    if time.monotonic() > deadline:
        raise RolloutError("rollout attribution exceeded its deadline")


def normalize_session_id(value: str) -> str:
    return value.lower() if UUID_RE.fullmatch(value) else value


def normalize_model_id(value: str) -> str:
    candidate = value.rsplit("/", 1)[-1]
    return MODEL_ALIASES.get(candidate, value)


def turn_model_id(payload: Mapping[str, object]) -> Optional[str]:
    for key in ("model", "model_id"):
        value = payload.get(key)
        if isinstance(value, str) and value:
            return value
    return None


def optional_id(payload: Mapping[str, object], key: str) -> Optional[str]:
    value = payload.get(key)
    if value is None:
        return None
    if not isinstance(value, str) or not value or len(value) > MAX_ID_CHARS:
        raise RolloutError("session metadata contains an invalid ID")
    return normalize_session_id(value)


def lifecycle_id(payload: Mapping[str, object]) -> Optional[str]:
    node_ids = {
        value
        for key in ("id", "thread_id")
        if (value := optional_id(payload, key)) is not None
    }
    if len(node_ids) > 1:
        raise RolloutError("session metadata node IDs disagree")
    return next(iter(node_ids), None) or optional_id(payload, "session_id")


def parent_thread_id(payload: Mapping[str, object]) -> Optional[str]:
    parents = set()
    if (parent := optional_id(payload, "parent_thread_id")) is not None:
        parents.add(parent)
    source = payload.get("source")
    if isinstance(source, dict):
        subagent = source.get("subagent")
        if isinstance(subagent, dict) and "thread_spawn" in subagent:
            spawn = subagent["thread_spawn"]
            if not isinstance(spawn, dict):
                raise RolloutError("session metadata has invalid thread-spawn provenance")
            parent = optional_id(spawn, "parent_thread_id")
            if parent is None:
                raise RolloutError("session metadata has incomplete thread-spawn provenance")
            parents.add(parent)
    if len(parents) > 1:
        raise RolloutError("session metadata parent hints disagree")
    return next(iter(parents), None)


def root_source_claim(payload: Mapping[str, object]) -> Optional[str]:
    thread_source = payload.get("thread_source")
    if thread_source is not None and not isinstance(thread_source, str):
        raise RolloutError("session metadata has invalid thread source")
    source = payload.get("source")
    if source is not None and not isinstance(source, (str, dict)):
        raise RolloutError("session metadata has invalid source")
    source_subagent = source == "subagent" or (
        isinstance(source, dict) and "subagent" in source
    )
    if thread_source == "subagent":
        return "subagent"
    if thread_source == "user":
        if source_subagent:
            raise RolloutError("session metadata source claims conflict")
        return "ordinary"
    if source_subagent:
        return "subagent"
    return None


def validate_lifecycle_claim(
    payload: Mapping[str, object],
    lifecycle_id: str,
    root_id: str,
    expected_parent: Optional[str],
) -> None:
    claim = root_source_claim(payload)
    root_hint = optional_id(payload, "session_id")
    parent_id = parent_thread_id(payload)
    if root_hint is not None and root_hint != root_id:
        raise RolloutError("session metadata names an inconsistent root")
    if parent_id is not None and parent_id != expected_parent:
        raise RolloutError("session metadata names an inconsistent parent")
    if expected_parent is None:
        if parent_id is not None or claim == "subagent":
            raise RolloutError("root metadata claims subagent provenance")
    elif claim == "ordinary" or root_hint == lifecycle_id:
        raise RolloutError("subagent metadata claims root provenance")


def normalized_turn_id(turn_id: str) -> str:
    try:
        return str(uuid.UUID(turn_id))
    except ValueError:
        return turn_id


def turn_order(turn_id: str) -> Optional[int]:
    try:
        parsed = uuid.UUID(turn_id)
    except ValueError:
        return None
    return parsed.int >> 80 if parsed.version == 7 else None


def open_rollout(path: Path, expected_identity: FileIdentity) -> BinaryIO:
    flags = os.O_RDONLY | os.O_NONBLOCK
    flags |= getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = -1
    try:
        descriptor = os.open(path, flags)
        metadata = os.fstat(descriptor)
        if not stat.S_ISREG(metadata.st_mode) or metadata.st_size > MAX_FILE_BYTES:
            raise RolloutError("selected rollout is not a bounded regular file")
        # Bind object identity while allowing an active rollout to append in place.
        if (metadata.st_dev, metadata.st_ino) != expected_identity:
            raise RolloutError("selected rollout was replaced after inventory")
        return os.fdopen(descriptor, "rb")
    except RolloutError:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise
    except OSError as exc:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise RolloutError("unable to open selected rollout") from exc


def validate_rollout_size(
    handle: BinaryIO,
    snapshot: FileSnapshot,
    read_limit: int,
    *,
    allow_partial_tail: bool,
) -> None:
    try:
        size = os.fstat(handle.fileno()).st_size
    except OSError as exc:
        raise RolloutError("unable to inspect selected rollout") from exc
    if size > MAX_FILE_BYTES:
        raise RolloutError("selected rollout exceeds a file bound")
    if allow_partial_tail:
        if size < read_limit:
            raise RolloutError("selected rollout was truncated after inventory")
    elif size != snapshot.inventory_size:
        raise RolloutError("archived rollout size changed after inventory")


def iter_records(
    path: Path,
    snapshot: FileSnapshot,
    deadline: float,
    *,
    allow_partial_tail: bool,
    byte_limit: int = MAX_FILE_BYTES,
) -> Iterator[Mapping[str, object]]:
    consumed = 0
    digest = hashlib.sha256()
    read_limit = snapshot.inventory_size
    if allow_partial_tail and snapshot.prefix_size is not None:
        read_limit = snapshot.prefix_size
    try:
        with open_rollout(path, snapshot.identity) as handle:
            validate_rollout_size(
                handle,
                snapshot,
                read_limit,
                allow_partial_tail=allow_partial_tail,
            )
            while consumed < read_limit:
                check_deadline(deadline)
                raw = handle.readline(
                    min(MAX_RECORD_BYTES + 1, read_limit - consumed)
                )
                if not raw:
                    raise RolloutError("selected rollout was truncated while reading")
                consumed += len(raw)
                if consumed > byte_limit or len(raw) > MAX_RECORD_BYTES:
                    raise RolloutError("selected rollout exceeds a read bound")
                if not raw.endswith(b"\n"):
                    if allow_partial_tail and snapshot.prefix_size is None:
                        snapshot.prefix_size = consumed - len(raw)
                        snapshot.prefix_sha256 = digest.hexdigest()
                        validate_rollout_size(
                            handle,
                            snapshot,
                            snapshot.prefix_size,
                            allow_partial_tail=True,
                        )
                        return
                    raise RolloutError("archived rollout has an incomplete record")
                digest.update(raw)
                try:
                    row = json.loads(raw)
                except (MemoryError, RecursionError, UnicodeError, ValueError) as exc:
                    raise RolloutError("selected rollout contains malformed JSON") from exc
                if not isinstance(row, dict):
                    raise RolloutError("selected rollout record is not an object")
                yield row
            validate_rollout_size(
                handle,
                snapshot,
                read_limit,
                allow_partial_tail=allow_partial_tail,
            )
            current_digest = digest.hexdigest()
            if snapshot.prefix_size is None:
                snapshot.prefix_size = consumed
                snapshot.prefix_sha256 = current_digest
            elif (
                consumed != snapshot.prefix_size
                or current_digest != snapshot.prefix_sha256
            ):
                raise RolloutError("selected rollout prefix changed after inventory")
    except RolloutError:
        raise
    except OSError as exc:
        raise RolloutError("unable to read selected rollout") from exc


def freeze_rollout_contents(
    active_paths: Set[Path],
    identities: Mapping[Path, FileSnapshot],
    deadline: float,
) -> None:
    for path in sorted(identities):
        for _row in iter_records(
            path,
            identities[path],
            deadline,
            allow_partial_tail=path in active_paths,
        ):
            pass


def probe_lifecycle_ids(
    path: Path,
    snapshot: FileSnapshot,
    active: bool,
    deadline: float,
) -> Tuple[str, ...]:
    lifecycle_ids = set()
    for row in iter_records(
        path,
        snapshot,
        deadline,
        allow_partial_tail=active,
        byte_limit=MAX_PROBE_BYTES,
    ):
        if row.get("type") != "session_meta":
            continue
        payload = row.get("payload")
        if not isinstance(payload, dict):
            raise RolloutError("session metadata payload is invalid")
        owner = lifecycle_id(payload)
        if owner is not None:
            lifecycle_ids.add(owner)
    if not lifecycle_ids:
        raise RolloutError("legacy rollout has no verified lifecycle owner")
    return tuple(sorted(lifecycle_ids))


def is_rollout_candidate(filename: str) -> bool:
    return filename.startswith("rollout-") and filename.endswith(".jsonl")


def validate_rollout_component(name: str, *, kind: str) -> None:
    if any(not character.isprintable() for character in name):
        raise RolloutError(f"rollout {kind} name is not printable")


def directory_open_flags() -> int:
    try:
        return os.O_RDONLY | os.O_CLOEXEC | os.O_DIRECTORY | os.O_NOFOLLOW
    except AttributeError as exc:
        raise RolloutError("descriptor-relative rollout inventory is unsupported") from exc


def scan_rollout_inventory(
    codex_home: Path,
    deadline: float,
) -> Tuple[InventorySnapshot, Dict[Path, os.stat_result]]:
    directories: Dict[Path, FileIdentity] = {}
    candidates: Dict[Path, CandidateSnapshot] = {}
    candidate_metadata: Dict[Path, os.stat_result] = {}
    entry_count = 0
    file_count = 0
    revalidation_entry_count = 0
    for root_name in ("sessions", "archived_sessions"):
        root = codex_home / root_name
        try:
            root_fd = os.open(root, directory_open_flags())
        except FileNotFoundError:
            continue
        except OSError as exc:
            raise RolloutError("unable to inspect rollout root") from exc

        root_directories: Dict[Path, FileIdentity] = {}
        directory_entries: Dict[Path, Tuple[DirectoryEntrySnapshot, ...]] = {}

        def walk_directory(directory_fd: int, directory: Path, depth: int) -> None:
            nonlocal entry_count, file_count
            check_deadline(deadline)
            try:
                directory_stat = os.fstat(directory_fd)
                directory_identity = (
                    directory_stat.st_dev,
                    directory_stat.st_ino,
                )
                if not stat.S_ISDIR(directory_stat.st_mode):
                    raise RolloutError("rollout inventory root is not a directory")
                directories[directory] = directory_identity
                root_directories[directory] = directory_identity
                relevant_entries: List[DirectoryEntrySnapshot] = []
                with os.scandir(directory_fd) as entries:
                    for entry in entries:
                        check_deadline(deadline)
                        entry_count += 1
                        if entry_count > MAX_ENTRIES:
                            raise RolloutError("rollout inventory is too large")
                        filename = entry.name
                        path = directory / filename
                        if is_rollout_candidate(filename):
                            file_count += 1
                            if file_count > MAX_FILES:
                                raise RolloutError(
                                    "rollout inventory has too many files"
                                )
                            validate_rollout_component(filename, kind="file")
                            try:
                                metadata = entry.stat(follow_symlinks=False)
                            except OSError as exc:
                                raise RolloutError(
                                    "unable to inspect rollout file"
                                ) from exc
                            if (
                                not stat.S_ISREG(metadata.st_mode)
                                or metadata.st_size > MAX_FILE_BYTES
                            ):
                                raise RolloutError(
                                    "rollout inventory contains an unsafe file"
                                )
                            candidate = CandidateSnapshot(
                                identity=(metadata.st_dev, metadata.st_ino),
                                size=metadata.st_size,
                                active=root_name == "sessions",
                            )
                            if path in candidates:
                                raise RolloutError(
                                    "rollout inventory contains a duplicate path"
                                )
                            candidates[path] = candidate
                            candidate_metadata[path] = metadata
                            relevant_entries.append(
                                DirectoryEntrySnapshot(
                                    filename,
                                    candidate.identity,
                                    stat.S_IFMT(metadata.st_mode),
                                )
                            )
                            continue
                        if entry.is_dir(follow_symlinks=False):
                            validate_rollout_component(filename, kind="directory")
                            if depth + 1 > MAX_DEPTH:
                                raise RolloutError("rollout inventory is too deep")
                            try:
                                metadata = entry.stat(follow_symlinks=False)
                                child_fd = os.open(
                                    filename,
                                    directory_open_flags(),
                                    dir_fd=directory_fd,
                                )
                            except OSError as exc:
                                raise RolloutError(
                                    "unable to open rollout inventory directory"
                                ) from exc
                            try:
                                opened_metadata = os.fstat(child_fd)
                                if (
                                    not stat.S_ISDIR(metadata.st_mode)
                                    or not stat.S_ISDIR(opened_metadata.st_mode)
                                    or (
                                        metadata.st_dev,
                                        metadata.st_ino,
                                    )
                                    != (
                                        opened_metadata.st_dev,
                                        opened_metadata.st_ino,
                                    )
                                ):
                                    raise RolloutError(
                                        "rollout inventory directory changed during traversal"
                                    )
                                relevant_entries.append(
                                    DirectoryEntrySnapshot(
                                        filename,
                                        (
                                            opened_metadata.st_dev,
                                            opened_metadata.st_ino,
                                        ),
                                        stat.S_IFMT(opened_metadata.st_mode),
                                    )
                                )
                                walk_directory(child_fd, path, depth + 1)
                            finally:
                                os.close(child_fd)
                final_directory_stat = os.fstat(directory_fd)
                if (
                    not stat.S_ISDIR(final_directory_stat.st_mode)
                    or (
                        final_directory_stat.st_dev,
                        final_directory_stat.st_ino,
                    )
                    != directory_identity
                ):
                    raise RolloutError(
                        "rollout inventory directory changed during traversal"
                    )
                directory_entries[directory] = tuple(
                    sorted(relevant_entries, key=lambda item: item.name)
                )
            except RolloutError:
                raise
            except OSError as exc:
                raise RolloutError("unable to inventory rollouts") from exc

        try:
            walk_directory(root_fd, root, 0)
            for directory, expected_identity in sorted(root_directories.items()):
                relative_parts = directory.relative_to(root).parts
                current_fd = os.dup(root_fd)
                try:
                    for component in relative_parts:
                        next_fd = os.open(
                            component,
                            directory_open_flags(),
                            dir_fd=current_fd,
                        )
                        os.close(current_fd)
                        current_fd = next_fd
                    previous_relevant_entries = None
                    directory_stable = False
                    for _attempt in range(MAX_INVENTORY_REVALIDATION_ATTEMPTS):
                        check_deadline(deadline)
                        before_metadata = os.fstat(current_fd)
                        if (
                            not stat.S_ISDIR(before_metadata.st_mode)
                            or (
                                before_metadata.st_dev,
                                before_metadata.st_ino,
                            )
                            != expected_identity
                        ):
                            raise RolloutError(
                                "rollout inventory directory changed during traversal"
                            )
                        before_signal = (
                            before_metadata.st_mtime_ns,
                            before_metadata.st_ctime_ns,
                            before_metadata.st_size,
                            before_metadata.st_nlink,
                        )
                        current_relevant_entries: List[DirectoryEntrySnapshot] = []
                        with os.scandir(current_fd) as entries:
                            for entry in entries:
                                revalidation_entry_count += 1
                                if revalidation_entry_count > MAX_REVALIDATION_ENTRIES:
                                    raise RolloutError(
                                        "rollout inventory revalidation is too large"
                                    )
                                check_deadline(deadline)
                                filename = entry.name
                                entry_metadata = os.stat(
                                    filename,
                                    dir_fd=current_fd,
                                    follow_symlinks=False,
                                )
                                is_directory = stat.S_ISDIR(entry_metadata.st_mode)
                                if is_directory:
                                    validate_rollout_component(
                                        filename,
                                        kind="directory",
                                    )
                                if is_rollout_candidate(filename) or is_directory:
                                    current_relevant_entries.append(
                                        DirectoryEntrySnapshot(
                                            filename,
                                            (
                                                entry_metadata.st_dev,
                                                entry_metadata.st_ino,
                                            ),
                                            stat.S_IFMT(entry_metadata.st_mode),
                                        )
                                    )
                        after_metadata = os.fstat(current_fd)
                        if (
                            not stat.S_ISDIR(after_metadata.st_mode)
                            or (
                                after_metadata.st_dev,
                                after_metadata.st_ino,
                            )
                            != expected_identity
                        ):
                            raise RolloutError(
                                "rollout inventory directory changed during traversal"
                            )
                        after_signal = (
                            after_metadata.st_mtime_ns,
                            after_metadata.st_ctime_ns,
                            after_metadata.st_size,
                            after_metadata.st_nlink,
                        )
                        relevant_entries = tuple(
                            sorted(
                                current_relevant_entries,
                                key=lambda item: item.name,
                            )
                        )
                        if directory_entries[directory] != relevant_entries:
                            raise RolloutError(
                                "rollout inventory changed during traversal"
                            )
                        if (
                            before_signal == after_signal
                            and previous_relevant_entries == relevant_entries
                        ):
                            directory_stable = True
                            break
                        previous_relevant_entries = relevant_entries
                    if not directory_stable:
                        raise RolloutError(
                            "rollout inventory directory did not stabilize"
                        )
                except RolloutError:
                    raise
                except OSError as exc:
                    raise RolloutError(
                        "unable to revalidate rollout inventory directory"
                    ) from exc
                finally:
                    os.close(current_fd)
        finally:
            os.close(root_fd)
    return InventorySnapshot(directories, candidates), candidate_metadata


def validate_rollout_inventory(
    expected: InventorySnapshot,
    actual: InventorySnapshot,
) -> None:
    if set(expected.candidates) != set(actual.candidates):
        raise RolloutError("rollout candidate set changed after inventory")
    for path, expected_candidate in expected.candidates.items():
        actual_candidate = actual.candidates[path]
        if (
            actual_candidate.identity != expected_candidate.identity
            or actual_candidate.active != expected_candidate.active
        ):
            raise RolloutError("rollout candidate identity changed after inventory")
        if not expected_candidate.active and actual_candidate.size != expected_candidate.size:
            raise RolloutError("archived rollout size changed after inventory")
    for path, expected_identity in expected.directories.items():
        if actual.directories.get(path) != expected_identity:
            raise RolloutError("rollout directory identity changed after inventory")


def inventory_rollouts(
    codex_home: Path,
    deadline: float,
) -> Tuple[
    Dict[str, List[Path]],
    Set[Path],
    Dict[Path, FileSnapshot],
    Set[Path],
    InventorySnapshot,
]:
    inventory, candidate_metadata = scan_rollout_inventory(codex_home, deadline)
    by_session: Dict[str, List[Path]] = {}
    active_paths: Set[Path] = set()
    identities: Dict[Path, FileSnapshot] = {}
    filename_owned_paths: Set[Path] = set()
    for path in sorted(inventory.candidates):
        candidate = inventory.candidates[path]
        metadata = candidate_metadata[path]
        ids = sorted({match.group(0).lower() for match in UUID_RE.finditer(path.name)})
        if len(ids) > 1:
            raise RolloutError("rollout filename contains multiple task IDs")
        if ids:
            filename_owned_paths.add(path)
        snapshot = FileSnapshot(
            identity=candidate.identity,
            inventory_size=metadata.st_size,
        )
        identities[path] = snapshot
        if candidate.active:
            active_paths.add(path)
        if not ids:
            ids.extend(
                probe_lifecycle_ids(
                    path,
                    snapshot,
                    candidate.active,
                    deadline,
                )
            )
        for session_id in ids:
            by_session.setdefault(session_id, []).append(path)
    for paths in by_session.values():
        paths.sort()
    # Establish every candidate's content baseline before publishing the inventory.
    freeze_rollout_contents(active_paths, identities, deadline)
    return (
        by_session,
        active_paths,
        identities,
        filename_owned_paths,
        inventory,
    )


def discover_metadata_children(
    rollouts: Mapping[str, Sequence[Path]],
    active_paths: Set[Path],
    identities: Mapping[Path, FileSnapshot],
    deadline: float,
) -> Dict[str, Set[str]]:
    children: Dict[str, Set[str]] = {}
    owned_paths = {owner: set(paths) for owner, paths in rollouts.items()}
    links = 0
    for path in sorted(identities):
        for row in iter_records(
            path,
            identities[path],
            deadline,
            allow_partial_tail=path in active_paths,
        ):
            if row.get("type") != "session_meta":
                continue
            payload = row.get("payload")
            if not isinstance(payload, dict):
                raise RolloutError("session metadata payload is invalid")
            owner = lifecycle_id(payload)
            if owner is None or path not in owned_paths.get(owner, ()):
                continue
            parent_id = parent_thread_id(payload)
            if parent_id is None:
                continue
            parent_children = children.setdefault(parent_id, set())
            if owner not in parent_children:
                links += 1
                if links > MAX_ENTRIES:
                    raise RolloutError("rollout metadata has too many family links")
                parent_children.add(owner)
    return children


def resolve_root(
    rollouts: Mapping[str, Sequence[Path]],
    active_paths: Set[Path],
    identities: Mapping[Path, FileSnapshot],
    filename_owned_paths: Set[Path],
    selected_id: str,
    deadline: float,
    chain: Optional[List[str]] = None,
) -> str:
    current = normalize_session_id(selected_id)
    visited = set()
    ordered_chain = []
    expected_root: Optional[str] = None
    while True:
        if current in visited:
            raise RolloutError("session metadata contains a parent cycle")
        visited.add(current)
        ordered_chain.append(current)
        roots = set()
        parents = set()
        root_proven = False
        strong_root = False
        root_claim: Optional[str] = None
        for path in rollouts.get(current, ()):
            checked_first_meta = False
            for row in iter_records(
                path,
                identities[path],
                deadline,
                allow_partial_tail=path in active_paths,
            ):
                if row.get("type") != "session_meta":
                    continue
                payload = row.get("payload")
                if not isinstance(payload, dict):
                    raise RolloutError("session metadata payload is invalid")
                owner = lifecycle_id(payload)
                if (
                    owner is not None
                    and path in filename_owned_paths
                    and not checked_first_meta
                ):
                    checked_first_meta = True
                    if owner != current:
                        raise RolloutError("rollout filename and owner disagree")
                if owner != current:
                    continue
                own_id = optional_id(payload, "id") or optional_id(payload, "thread_id")
                root_id = optional_id(payload, "session_id")
                parent_id = parent_thread_id(payload)
                claim = root_source_claim(payload)
                if claim is not None:
                    if root_claim is not None and claim != root_claim:
                        raise RolloutError("session metadata root claims conflict")
                    root_claim = claim
                if root_id == current and parent_id is not None:
                    raise RolloutError("root metadata names a parent")
                if root_id == current and parent_id is None:
                    root_proven = True
                    strong_root = True
                if (
                    own_id == current
                    and root_id is None
                    and parent_id is None
                ):
                    root_proven = True
                if own_id == current and root_id not in (None, current):
                    roots.add(root_id)
                if parent_id == current:
                    raise RolloutError("session metadata is self-parented")
                if parent_id is not None:
                    parents.add(parent_id)
                if len(roots) > 1 or len(parents) > 1:
                    raise RolloutError("session metadata provenance conflicts")
        if strong_root and (roots or parents):
            raise RolloutError("session metadata mixes root and subagent provenance")
        if parents and root_claim == "ordinary":
            raise RolloutError("subagent metadata claims root provenance")
        if roots:
            hinted_root = next(iter(roots))
            if hinted_root not in rollouts or expected_root not in (None, hinted_root):
                raise RolloutError("root task rollout is unavailable or inconsistent")
            expected_root = hinted_root
            if not parents:
                raise RolloutError("root hint lacks parent provenance")
        if not parents:
            if expected_root is not None and current != expected_root:
                raise RolloutError("parent chain misses its root")
            if not root_proven or root_claim == "subagent":
                raise RolloutError("root task identity is unverified")
            if chain is not None:
                chain.extend(ordered_chain)
            return current
        current = next(iter(parents))
        if current not in rollouts:
            raise RolloutError("parent task rollout is unavailable")


def collect_votes(
    rollouts: Mapping[str, Sequence[Path]],
    active_paths: Set[Path],
    identities: Mapping[Path, FileSnapshot],
    filename_owned_paths: Set[Path],
    root_id: str,
    seed_ids: Sequence[str],
    deadline: float,
) -> Dict[TurnKey, Vote]:
    metadata_children = discover_metadata_children(
        rollouts,
        active_paths,
        identities,
        deadline,
    )
    pending = deque([root_id])
    scheduled = {root_id}
    for seed_id in seed_ids:
        seed_id = normalize_session_id(seed_id)
        if seed_id not in rollouts:
            raise RolloutError("selected family rollout is unavailable")
        if seed_id not in scheduled:
            pending.append(seed_id)
            scheduled.add(seed_id)
    resolved_roots: Dict[str, str] = {}
    resolved_parents: Dict[str, Optional[str]] = {}

    def resolve_binding(session_id: str) -> Tuple[str, Optional[str]]:
        if session_id not in resolved_parents:
            resolved_chain: List[str] = []
            resolved_root = resolve_root(
                rollouts,
                active_paths,
                identities,
                filename_owned_paths,
                session_id,
                deadline,
                resolved_chain,
            )
            for index, member_id in enumerate(resolved_chain):
                member_parent = (
                    resolved_chain[index + 1]
                    if index + 1 < len(resolved_chain)
                    else None
                )
                if resolved_roots.get(member_id, resolved_root) != resolved_root:
                    raise RolloutError("task root binding changed during attribution")
                if (
                    member_id in resolved_parents
                    and resolved_parents[member_id] != member_parent
                ):
                    raise RolloutError("task parent binding changed during attribution")
                resolved_roots[member_id] = resolved_root
                resolved_parents[member_id] = member_parent
        return resolved_roots[session_id], resolved_parents[session_id]

    visited = set()
    processed_paths: Set[Path] = set()
    file_votes: Dict[Tuple[str, str, Path], Vote] = {}
    turn_keys: Set[TurnKey] = set()
    while pending:
        session_id = pending.popleft()
        if session_id in visited:
            continue
        visited.add(session_id)
        session_root, _session_parent = resolve_binding(session_id)
        if session_root != root_id:
            raise RolloutError("scheduled lifecycle is outside the task family")
        for child_id in sorted(metadata_children.get(session_id, ())):
            child_root, child_parent = resolve_binding(child_id)
            if child_root != root_id or child_parent != session_id:
                raise RolloutError("session metadata child binding is inconsistent")
            if child_id not in scheduled:
                pending.append(child_id)
                scheduled.add(child_id)
        for path in rollouts.get(session_id, ()):
            if path in processed_paths:
                continue
            processed_paths.add(path)
            checked_first_meta = False
            vote_session_id: Optional[str] = (
                session_id if path in filename_owned_paths else None
            )
            for row in iter_records(
                path,
                identities[path],
                deadline,
                allow_partial_tail=path in active_paths,
            ):
                record_type = row.get("type")
                payload = row.get("payload")
                if record_type is not None and not isinstance(record_type, str):
                    raise RolloutError("rollout record type is invalid")
                if record_type in {"session_meta", "event_msg", "turn_context"} and not isinstance(payload, dict):
                    raise RolloutError("rollout record payload is invalid")
                if not isinstance(payload, dict):
                    continue
                if record_type == "session_meta":
                    owner = lifecycle_id(payload)
                    if owner is None:
                        vote_session_id = None
                    else:
                        if owner not in rollouts:
                            raise RolloutError("replayed lifecycle rollout is unavailable")
                        owner_root, owner_parent = resolve_binding(owner)
                        if owner_root != root_id:
                            raise RolloutError("replayed lifecycle is outside the task family")
                        validate_lifecycle_claim(
                            payload,
                            owner,
                            root_id,
                            owner_parent,
                        )
                        if path in filename_owned_paths and not checked_first_meta:
                            checked_first_meta = True
                            if owner != session_id:
                                raise RolloutError("rollout filename and owner disagree")
                        vote_session_id = owner
                        if owner not in scheduled:
                            pending.append(owner)
                            scheduled.add(owner)
                if record_type == "event_msg" and payload.get("type") == "sub_agent_activity":
                    child_id = payload.get("agent_thread_id")
                    if not isinstance(child_id, str) or not child_id or len(child_id) > MAX_ID_CHARS:
                        raise RolloutError("subagent activity task ID is invalid")
                    child_id = normalize_session_id(child_id)
                    if child_id not in rollouts:
                        raise RolloutError("referenced subagent rollout is unavailable")
                    child_root, _child_parent = resolve_binding(child_id)
                    if child_root != root_id:
                        raise RolloutError("referenced subagent is outside the task family")
                    if child_id not in scheduled:
                        pending.append(child_id)
                        scheduled.add(child_id)
                if record_type != "turn_context":
                    continue
                if vote_session_id is None:
                    raise RolloutError("turn context has no verified lifecycle owner")
                turn_id = payload.get("turn_id")
                model = turn_model_id(payload)
                effort = payload.get("effort")
                if not isinstance(turn_id, str) or not turn_id:
                    raise RolloutError("turn context has no task ID")
                if not all(isinstance(value, str) and value for value in (model, effort)):
                    continue
                if len(turn_id) > MAX_ID_CHARS or len(model) > 128 or len(effort) > 64:
                    raise RolloutError("turn context field exceeds its limit")
                model = normalize_model_id(model)
                normalized_id = normalized_turn_id(turn_id)
                turn_key = (vote_session_id, normalized_id)
                if turn_key not in turn_keys and len(turn_keys) >= MAX_TURNS:
                    raise RolloutError("task family has too many unique turns")
                turn_keys.add(turn_key)
                file_key = (vote_session_id, normalized_id, path)
                if file_key not in file_votes and len(file_votes) >= MAX_VOTE_COPIES:
                    raise RolloutError("task family has too many replayed turn copies")
                file_votes[file_key] = Vote((model, effort), turn_order(turn_id))
    votes: Dict[TurnKey, Vote] = {}
    for (session_id, turn_id, _path), vote in file_votes.items():
        key = (session_id, turn_id)
        previous = votes.get(key)
        if previous is not None and previous.pair != vote.pair:
            raise RolloutError("the same turn conflicts across rollout files")
        votes[key] = vote
    return votes


def choose_pair(votes: Iterable[Vote]) -> Optional[Pair]:
    votes = list(votes)
    if not votes:
        return None
    counts = Counter(vote.pair for vote in votes)
    highest = max(counts.values())
    candidates = {pair for pair, count in counts.items() if count == highest}
    if len(candidates) == 1:
        return next(iter(candidates))
    tied = [vote for vote in votes if vote.pair in candidates]
    if any(vote.turn_order is None for vote in tied):
        return None
    latest = max(vote.turn_order for vote in tied)
    latest_pairs = {vote.pair for vote in tied if vote.turn_order == latest}
    return next(iter(latest_pairs)) if len(latest_pairs) == 1 else None


def label_for(pair: Optional[Pair]) -> str:
    if pair is None:
        return FALLBACK_LABEL
    model, effort = pair
    if model not in MODEL_LABELS or effort not in EFFORT_LABELS:
        return FALLBACK_LABEL
    return "{} {}".format(MODEL_LABELS[model], EFFORT_LABELS[effort])


def revalidate_rollout_contents(
    active_paths: Set[Path],
    identities: Mapping[Path, FileSnapshot],
    deadline: float,
) -> None:
    freeze_rollout_contents(active_paths, identities, deadline)


def render_sentence(codex_home: Path, session_id: Optional[str]) -> str:
    if not session_id or len(session_id) > MAX_ID_CHARS:
        return SENTENCE.format(FALLBACK_LABEL)
    try:
        deadline = time.monotonic() + DEADLINE_SECONDS
        (
            rollouts,
            active_paths,
            identities,
            filename_owned_paths,
            inventory,
        ) = inventory_rollouts(codex_home, deadline)
        selected_id = normalize_session_id(session_id)
        if selected_id not in rollouts:
            return SENTENCE.format(FALLBACK_LABEL)
        chain: List[str] = []
        root_id = resolve_root(
            rollouts,
            active_paths,
            identities,
            filename_owned_paths,
            selected_id,
            deadline,
            chain,
        )
        votes = collect_votes(
            rollouts,
            active_paths,
            identities,
            filename_owned_paths,
            root_id,
            tuple(reversed(chain)),
            deadline,
        )
        revalidate_rollout_contents(active_paths, identities, deadline)
        final_inventory, _final_metadata = scan_rollout_inventory(
            codex_home,
            deadline,
        )
        validate_rollout_inventory(inventory, final_inventory)
        revalidate_rollout_contents(active_paths, identities, deadline)
        check_deadline(deadline)
    except (MemoryError, RecursionError, RolloutError):
        return SENTENCE.format(FALLBACK_LABEL)
    return SENTENCE.format(label_for(choose_pair(votes.values())))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Render the Codex PR attribution sentence.")
    parser.add_argument("--session-id", help="Task ID; defaults to CODEX_THREAD_ID.")
    parser.add_argument(
        "--codex-home",
        type=Path,
        default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")),
        help=argparse.SUPPRESS,
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    session_id = args.session_id or os.environ.get("CODEX_THREAD_ID")
    print(render_sentence(args.codex_home.expanduser(), session_id))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
