#!/usr/bin/env python3
"""Render the Codex-authored PR attribution sentence from rollout history."""

from __future__ import annotations

import argparse
from collections import Counter, deque
from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import stat
import time
from typing import (
    BinaryIO,
    Dict,
    Iterable,
    Iterator,
    List,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
)
import uuid


FALLBACK_LABEL = "GPT-5.6 Sol Ultra"
SENTENCE = "This PR is purely generated by LLM: OpenAI Codex ({})."
MAX_RECORD_BYTES = 1024 * 1024
MAX_FILE_BYTES = 512 * 1024 * 1024
MAX_PROBE_BYTES = 1024 * 1024
MAX_ENTRIES = 100_000
MAX_FILES = 50_000
MAX_DEPTH = 8
MAX_TURNS = 100_000
MAX_VOTE_COPIES = 200_000
MAX_ID_CHARS = 1024
DEADLINE_SECONDS = 30.0
UUID_RE = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)
MODEL_LABELS = {
    "gpt-5.5": "GPT-5.5",
    "gpt-5.6-sol": "GPT-5.6 Sol",
    "gpt-5.6-terra": "GPT-5.6 Terra",
}
EFFORT_LABELS = {
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "xhigh": "Extra High",
    "max": "Max",
    "ultra": "Ultra",
}
Pair = Tuple[str, str]
TurnKey = Tuple[str, str]
FileIdentity = Tuple[int, int]


class RolloutError(RuntimeError):
    """The selected task family cannot supply complete attribution evidence."""


@dataclass(frozen=True)
class Vote:
    pair: Pair
    turn_order: Optional[int]


def check_deadline(deadline: float) -> None:
    if time.monotonic() > deadline:
        raise RolloutError("rollout attribution exceeded its deadline")


def normalize_session_id(value: str) -> str:
    return value.lower() if UUID_RE.fullmatch(value) else value


def optional_id(payload: Mapping[str, object], key: str) -> Optional[str]:
    value = payload.get(key)
    if value is None:
        return None
    if not isinstance(value, str) or not value or len(value) > MAX_ID_CHARS:
        raise RolloutError("session metadata contains an invalid ID")
    return normalize_session_id(value)


def lifecycle_id(payload: Mapping[str, object]) -> Optional[str]:
    node_ids = {
        value
        for key in ("id", "thread_id")
        if (value := optional_id(payload, key)) is not None
    }
    if len(node_ids) > 1:
        raise RolloutError("session metadata node IDs disagree")
    return next(iter(node_ids), None) or optional_id(payload, "session_id")


def parent_thread_id(payload: Mapping[str, object]) -> Optional[str]:
    parents = set()
    if (parent := optional_id(payload, "parent_thread_id")) is not None:
        parents.add(parent)
    source = payload.get("source")
    if isinstance(source, dict):
        subagent = source.get("subagent")
        if isinstance(subagent, dict) and "thread_spawn" in subagent:
            spawn = subagent["thread_spawn"]
            if not isinstance(spawn, dict):
                raise RolloutError("session metadata has invalid thread-spawn provenance")
            parent = optional_id(spawn, "parent_thread_id")
            if parent is None:
                raise RolloutError("session metadata has incomplete thread-spawn provenance")
            parents.add(parent)
    if len(parents) > 1:
        raise RolloutError("session metadata parent hints disagree")
    return next(iter(parents), None)


def root_source_claim(payload: Mapping[str, object]) -> Optional[str]:
    thread_source = payload.get("thread_source")
    if thread_source is not None and not isinstance(thread_source, str):
        raise RolloutError("session metadata has invalid thread source")
    source = payload.get("source")
    if source is not None and not isinstance(source, (str, dict)):
        raise RolloutError("session metadata has invalid source")
    source_subagent = source == "subagent" or (
        isinstance(source, dict) and "subagent" in source
    )
    if thread_source == "subagent":
        return "subagent"
    if thread_source == "user":
        if source_subagent:
            raise RolloutError("session metadata source claims conflict")
        return "ordinary"
    if source_subagent:
        return "subagent"
    return None


def validate_lifecycle_claim(
    payload: Mapping[str, object],
    lifecycle_id: str,
    root_id: str,
    expected_parent: Optional[str],
) -> None:
    claim = root_source_claim(payload)
    root_hint = optional_id(payload, "session_id")
    parent_id = parent_thread_id(payload)
    if root_hint is not None and root_hint != root_id:
        raise RolloutError("session metadata names an inconsistent root")
    if parent_id is not None and parent_id != expected_parent:
        raise RolloutError("session metadata names an inconsistent parent")
    if expected_parent is None:
        if parent_id is not None or claim == "subagent":
            raise RolloutError("root metadata claims subagent provenance")
    elif claim == "ordinary" or root_hint == lifecycle_id:
        raise RolloutError("subagent metadata claims root provenance")


def normalized_turn_id(turn_id: str) -> str:
    try:
        return str(uuid.UUID(turn_id))
    except ValueError:
        return turn_id


def turn_order(turn_id: str) -> Optional[int]:
    try:
        parsed = uuid.UUID(turn_id)
    except ValueError:
        return None
    return parsed.int >> 80 if parsed.version == 7 else None


def open_rollout(path: Path, expected_identity: FileIdentity) -> BinaryIO:
    flags = os.O_RDONLY | os.O_NONBLOCK
    flags |= getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = -1
    try:
        descriptor = os.open(path, flags)
        metadata = os.fstat(descriptor)
        if not stat.S_ISREG(metadata.st_mode) or metadata.st_size > MAX_FILE_BYTES:
            raise RolloutError("selected rollout is not a bounded regular file")
        # Bind object identity while allowing an active rollout to append in place.
        if (metadata.st_dev, metadata.st_ino) != expected_identity:
            raise RolloutError("selected rollout was replaced after inventory")
        return os.fdopen(descriptor, "rb")
    except RolloutError:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise
    except OSError as exc:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise RolloutError("unable to open selected rollout") from exc


def iter_records(
    path: Path,
    expected_identity: FileIdentity,
    deadline: float,
    *,
    allow_partial_tail: bool,
    byte_limit: int = MAX_FILE_BYTES,
) -> Iterator[Mapping[str, object]]:
    consumed = 0
    try:
        with open_rollout(path, expected_identity) as handle:
            while True:
                check_deadline(deadline)
                raw = handle.readline(MAX_RECORD_BYTES + 1)
                if not raw:
                    return
                consumed += len(raw)
                if consumed > byte_limit or len(raw) > MAX_RECORD_BYTES:
                    raise RolloutError("selected rollout exceeds a read bound")
                if not raw.endswith(b"\n"):
                    if allow_partial_tail:
                        return
                    raise RolloutError("archived rollout has an incomplete record")
                try:
                    row = json.loads(raw)
                except (MemoryError, RecursionError, UnicodeError, ValueError) as exc:
                    raise RolloutError("selected rollout contains malformed JSON") from exc
                if not isinstance(row, dict):
                    raise RolloutError("selected rollout record is not an object")
                yield row
    except RolloutError:
        raise
    except OSError as exc:
        raise RolloutError("unable to read selected rollout") from exc


def probe_owner(
    path: Path,
    expected_identity: FileIdentity,
    active: bool,
    deadline: float,
) -> Optional[str]:
    try:
        for row in iter_records(
            path,
            expected_identity,
            deadline,
            allow_partial_tail=active,
            byte_limit=MAX_PROBE_BYTES,
        ):
            if row.get("type") != "session_meta":
                continue
            payload = row.get("payload")
            if not isinstance(payload, dict):
                return None
            owner = lifecycle_id(payload)
            if owner is not None:
                return owner
    except RolloutError:
        return None
    return None


def inventory_rollouts(
    codex_home: Path,
    deadline: float,
) -> Tuple[Dict[str, List[Path]], Set[Path], Dict[Path, FileIdentity], Set[Path]]:
    by_session: Dict[str, List[Path]] = {}
    active_paths: Set[Path] = set()
    identities: Dict[Path, FileIdentity] = {}
    filename_owned_paths: Set[Path] = set()
    entry_count = 0
    file_count = 0
    for root_name in ("sessions", "archived_sessions"):
        root = codex_home / root_name
        try:
            root_stat = root.lstat()
        except FileNotFoundError:
            continue
        except OSError as exc:
            raise RolloutError("unable to inspect rollout root") from exc
        if not stat.S_ISDIR(root_stat.st_mode):
            raise RolloutError("rollout root is not a directory")
        pending = [(root, 0)]
        while pending:
            directory, depth = pending.pop()
            check_deadline(deadline)
            try:
                with os.scandir(directory) as entries:
                    for entry in entries:
                        check_deadline(deadline)
                        entry_count += 1
                        if entry_count > MAX_ENTRIES:
                            raise RolloutError("rollout inventory is too large")
                        if entry.is_dir(follow_symlinks=False):
                            if depth + 1 > MAX_DEPTH:
                                raise RolloutError("rollout inventory is too deep")
                            pending.append((Path(entry.path), depth + 1))
                            continue
                        filename = entry.name
                        if not filename.startswith("rollout-") or not filename.endswith(".jsonl"):
                            continue
                        file_count += 1
                        if file_count > MAX_FILES:
                            raise RolloutError("rollout inventory has too many files")
                        if any(not character.isprintable() for character in filename):
                            raise RolloutError("rollout filename is not printable")
                        try:
                            metadata = entry.stat(follow_symlinks=False)
                        except OSError as exc:
                            raise RolloutError("unable to inspect rollout file") from exc
                        if not stat.S_ISREG(metadata.st_mode) or metadata.st_size > MAX_FILE_BYTES:
                            raise RolloutError("rollout inventory contains an unsafe file")
                        ids = sorted({match.group(0).lower() for match in UUID_RE.finditer(filename)})
                        if len(ids) > 1:
                            raise RolloutError("rollout filename contains multiple task IDs")
                        path = Path(entry.path)
                        if ids:
                            filename_owned_paths.add(path)
                        identity = (metadata.st_dev, metadata.st_ino)
                        identities[path] = identity
                        active = root_name == "sessions"
                        if active:
                            active_paths.add(path)
                        if not ids:
                            owner = probe_owner(path, identity, active, deadline)
                            if owner is not None:
                                ids.append(owner)
                        for session_id in ids:
                            by_session.setdefault(session_id, []).append(path)
            except RolloutError:
                raise
            except OSError as exc:
                raise RolloutError("unable to inventory rollouts") from exc
    for paths in by_session.values():
        paths.sort()
    return by_session, active_paths, identities, filename_owned_paths


def resolve_root(
    rollouts: Mapping[str, Sequence[Path]],
    active_paths: Set[Path],
    identities: Mapping[Path, FileIdentity],
    selected_id: str,
    deadline: float,
    chain: Optional[List[str]] = None,
) -> str:
    current = normalize_session_id(selected_id)
    visited = set()
    ordered_chain = []
    expected_root: Optional[str] = None
    while True:
        if current in visited:
            raise RolloutError("session metadata contains a parent cycle")
        visited.add(current)
        ordered_chain.append(current)
        roots = set()
        parents = set()
        root_proven = False
        strong_root = False
        root_claim: Optional[str] = None
        for path in rollouts.get(current, ()):
            checked_first_meta = False
            for row in iter_records(
                path,
                identities[path],
                deadline,
                allow_partial_tail=path in active_paths,
            ):
                if row.get("type") != "session_meta":
                    continue
                payload = row.get("payload")
                if not isinstance(payload, dict):
                    raise RolloutError("session metadata payload is invalid")
                owner = lifecycle_id(payload)
                if owner is not None and not checked_first_meta:
                    checked_first_meta = True
                    if owner != current:
                        raise RolloutError("rollout filename and owner disagree")
                if owner != current:
                    continue
                own_id = optional_id(payload, "id") or optional_id(payload, "thread_id")
                root_id = optional_id(payload, "session_id")
                parent_id = parent_thread_id(payload)
                claim = root_source_claim(payload)
                if claim is not None:
                    if root_claim is not None and claim != root_claim:
                        raise RolloutError("session metadata root claims conflict")
                    root_claim = claim
                if root_id == current and parent_id is not None:
                    raise RolloutError("root metadata names a parent")
                if root_id == current and parent_id is None:
                    root_proven = True
                    strong_root = True
                if (
                    own_id == current
                    and root_id is None
                    and parent_id is None
                ):
                    root_proven = True
                if own_id == current and root_id not in (None, current):
                    roots.add(root_id)
                if parent_id == current:
                    raise RolloutError("session metadata is self-parented")
                if parent_id is not None:
                    parents.add(parent_id)
                if len(roots) > 1 or len(parents) > 1:
                    raise RolloutError("session metadata provenance conflicts")
        if strong_root and (roots or parents):
            raise RolloutError("session metadata mixes root and subagent provenance")
        if parents and root_claim == "ordinary":
            raise RolloutError("subagent metadata claims root provenance")
        if roots:
            hinted_root = next(iter(roots))
            if hinted_root not in rollouts or expected_root not in (None, hinted_root):
                raise RolloutError("root task rollout is unavailable or inconsistent")
            expected_root = hinted_root
            if not parents:
                raise RolloutError("root hint lacks parent provenance")
        if not parents:
            if expected_root is not None and current != expected_root:
                raise RolloutError("parent chain misses its root")
            if not root_proven or root_claim == "subagent":
                raise RolloutError("root task identity is unverified")
            if chain is not None:
                chain.extend(ordered_chain)
            return current
        current = next(iter(parents))
        if current not in rollouts:
            raise RolloutError("parent task rollout is unavailable")


def collect_votes(
    rollouts: Mapping[str, Sequence[Path]],
    active_paths: Set[Path],
    identities: Mapping[Path, FileIdentity],
    filename_owned_paths: Set[Path],
    root_id: str,
    seed_ids: Sequence[str],
    deadline: float,
) -> Dict[TurnKey, Vote]:
    pending = deque([root_id])
    scheduled = {root_id}
    for seed_id in seed_ids:
        seed_id = normalize_session_id(seed_id)
        if seed_id not in rollouts:
            raise RolloutError("selected family rollout is unavailable")
        if seed_id not in scheduled:
            pending.append(seed_id)
            scheduled.add(seed_id)
    resolved_roots: Dict[str, str] = {}
    resolved_parents: Dict[str, Optional[str]] = {}

    def resolve_binding(session_id: str) -> Tuple[str, Optional[str]]:
        if session_id not in resolved_parents:
            resolved_chain: List[str] = []
            resolved_root = resolve_root(
                rollouts,
                active_paths,
                identities,
                session_id,
                deadline,
                resolved_chain,
            )
            for index, member_id in enumerate(resolved_chain):
                member_parent = (
                    resolved_chain[index + 1]
                    if index + 1 < len(resolved_chain)
                    else None
                )
                if resolved_roots.get(member_id, resolved_root) != resolved_root:
                    raise RolloutError("task root binding changed during attribution")
                if (
                    member_id in resolved_parents
                    and resolved_parents[member_id] != member_parent
                ):
                    raise RolloutError("task parent binding changed during attribution")
                resolved_roots[member_id] = resolved_root
                resolved_parents[member_id] = member_parent
        return resolved_roots[session_id], resolved_parents[session_id]

    visited = set()
    file_votes: Dict[Tuple[str, str, Path], Vote] = {}
    turn_keys: Set[TurnKey] = set()
    while pending:
        session_id = pending.popleft()
        if session_id in visited:
            continue
        visited.add(session_id)
        session_root, _session_parent = resolve_binding(session_id)
        if session_root != root_id:
            raise RolloutError("scheduled lifecycle is outside the task family")
        for path in rollouts.get(session_id, ()):
            checked_first_meta = False
            vote_session_id: Optional[str] = (
                session_id if path in filename_owned_paths else None
            )
            for row in iter_records(
                path,
                identities[path],
                deadline,
                allow_partial_tail=path in active_paths,
            ):
                record_type = row.get("type")
                payload = row.get("payload")
                if record_type is not None and not isinstance(record_type, str):
                    raise RolloutError("rollout record type is invalid")
                if record_type in {"session_meta", "event_msg", "turn_context"} and not isinstance(payload, dict):
                    raise RolloutError("rollout record payload is invalid")
                if not isinstance(payload, dict):
                    continue
                if record_type == "session_meta":
                    owner = lifecycle_id(payload)
                    if owner is None:
                        vote_session_id = None
                    else:
                        if owner not in rollouts:
                            raise RolloutError("replayed lifecycle rollout is unavailable")
                        owner_root, owner_parent = resolve_binding(owner)
                        if owner_root != root_id:
                            raise RolloutError("replayed lifecycle is outside the task family")
                        validate_lifecycle_claim(
                            payload,
                            owner,
                            root_id,
                            owner_parent,
                        )
                        if not checked_first_meta:
                            checked_first_meta = True
                            if owner != session_id:
                                raise RolloutError("rollout filename and owner disagree")
                        vote_session_id = owner
                        if owner not in scheduled:
                            pending.append(owner)
                            scheduled.add(owner)
                if record_type == "event_msg" and payload.get("type") == "sub_agent_activity":
                    child_id = payload.get("agent_thread_id")
                    if not isinstance(child_id, str) or not child_id or len(child_id) > MAX_ID_CHARS:
                        raise RolloutError("subagent activity task ID is invalid")
                    child_id = normalize_session_id(child_id)
                    if child_id not in rollouts:
                        raise RolloutError("referenced subagent rollout is unavailable")
                    child_root, _child_parent = resolve_binding(child_id)
                    if child_root != root_id:
                        raise RolloutError("referenced subagent is outside the task family")
                    if child_id not in scheduled:
                        pending.append(child_id)
                        scheduled.add(child_id)
                if record_type != "turn_context":
                    continue
                if vote_session_id is None:
                    raise RolloutError("turn context has no verified lifecycle owner")
                turn_id = payload.get("turn_id")
                model = payload.get("model")
                effort = payload.get("effort")
                if not isinstance(turn_id, str) or not turn_id:
                    raise RolloutError("turn context has no task ID")
                if not all(isinstance(value, str) and value for value in (model, effort)):
                    continue
                if len(turn_id) > MAX_ID_CHARS or len(model) > 128 or len(effort) > 64:
                    raise RolloutError("turn context field exceeds its limit")
                normalized_id = normalized_turn_id(turn_id)
                turn_key = (vote_session_id, normalized_id)
                if turn_key not in turn_keys and len(turn_keys) >= MAX_TURNS:
                    raise RolloutError("task family has too many unique turns")
                turn_keys.add(turn_key)
                file_key = (vote_session_id, normalized_id, path)
                if file_key not in file_votes and len(file_votes) >= MAX_VOTE_COPIES:
                    raise RolloutError("task family has too many replayed turn copies")
                file_votes[file_key] = Vote((model, effort), turn_order(turn_id))
    votes: Dict[TurnKey, Vote] = {}
    for (session_id, turn_id, _path), vote in file_votes.items():
        key = (session_id, turn_id)
        previous = votes.get(key)
        if previous is not None and previous.pair != vote.pair:
            raise RolloutError("the same turn conflicts across rollout files")
        votes[key] = vote
    return votes


def choose_pair(votes: Iterable[Vote]) -> Optional[Pair]:
    votes = list(votes)
    if not votes:
        return None
    counts = Counter(vote.pair for vote in votes)
    highest = max(counts.values())
    candidates = {pair for pair, count in counts.items() if count == highest}
    if len(candidates) == 1:
        return next(iter(candidates))
    tied = [vote for vote in votes if vote.pair in candidates]
    if any(vote.turn_order is None for vote in tied):
        return None
    latest = max(vote.turn_order for vote in tied)
    latest_pairs = {vote.pair for vote in tied if vote.turn_order == latest}
    return next(iter(latest_pairs)) if len(latest_pairs) == 1 else None


def label_for(pair: Optional[Pair]) -> str:
    if pair is None:
        return FALLBACK_LABEL
    model, effort = pair
    if model not in MODEL_LABELS or effort not in EFFORT_LABELS:
        return FALLBACK_LABEL
    return "{} {}".format(MODEL_LABELS[model], EFFORT_LABELS[effort])


def render_sentence(codex_home: Path, session_id: Optional[str]) -> str:
    if not session_id or len(session_id) > MAX_ID_CHARS:
        return SENTENCE.format(FALLBACK_LABEL)
    try:
        deadline = time.monotonic() + DEADLINE_SECONDS
        rollouts, active_paths, identities, filename_owned_paths = inventory_rollouts(
            codex_home,
            deadline,
        )
        selected_id = normalize_session_id(session_id)
        if selected_id not in rollouts:
            return SENTENCE.format(FALLBACK_LABEL)
        chain: List[str] = []
        root_id = resolve_root(
            rollouts,
            active_paths,
            identities,
            selected_id,
            deadline,
            chain,
        )
        votes = collect_votes(
            rollouts,
            active_paths,
            identities,
            filename_owned_paths,
            root_id,
            tuple(reversed(chain)),
            deadline,
        )
        check_deadline(deadline)
    except (MemoryError, RecursionError, RolloutError):
        return SENTENCE.format(FALLBACK_LABEL)
    return SENTENCE.format(label_for(choose_pair(votes.values())))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Render the Codex PR attribution sentence.")
    parser.add_argument("--session-id", help="Task ID; defaults to CODEX_THREAD_ID.")
    parser.add_argument(
        "--codex-home",
        type=Path,
        default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")),
        help=argparse.SUPPRESS,
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    session_id = args.session_id or os.environ.get("CODEX_THREAD_ID")
    print(render_sentence(args.codex_home.expanduser(), session_id))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
