from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = (
    REPO_ROOT
    / "skills"
    / "codex-session-mining"
    / "scripts"
    / "pr_attribution.py"
)
ROOT = "11111111-1111-4111-8111-111111111111"
CHILD = "22222222-2222-4222-8222-222222222222"
GRANDCHILD = "33333333-3333-4333-8333-333333333333"
UNRELATED = "44444444-4444-4444-8444-444444444444"
FALLBACK = "This PR is purely generated by LLM: OpenAI Codex (GPT-5.6 Sol Ultra).\n"


def sentence(label: str) -> str:
    return f"This PR is purely generated by LLM: OpenAI Codex ({label}).\n"


def write_rollout(
    codex_home: Path,
    session_id: str,
    rows: list[dict],
    *,
    relative_path: Path | None = None,
    add_owner_meta: bool = True,
) -> Path:
    path = codex_home / (
        relative_path
        or Path(
            "sessions",
            "2026",
            "08",
            "11",
            f"rollout-2026-08-11T12-00-00-{session_id}.jsonl",
        )
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    if add_owner_meta and not any(row.get("type") == "session_meta" for row in rows):
        rows = [meta(session_id, session_id), *rows]
    path.write_text(
        "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )
    return path


def meta(
    session_id: str,
    root_id: str | None,
    *,
    parent_id: str | None = None,
    source: object | None = None,
) -> dict:
    payload: dict[str, object] = {"id": session_id}
    if root_id is not None:
        payload["session_id"] = root_id
    if parent_id is not None:
        payload["parent_thread_id"] = parent_id
        payload["source"] = {
            "subagent": {"thread_spawn": {"parent_thread_id": parent_id}}
        }
    elif source is not None:
        payload["source"] = source
    return {"type": "session_meta", "payload": payload}


def turn(turn_id: str, effort: str, *, model: str = "gpt-5.6-sol", timestamp: str | None = None) -> dict:
    row: dict[str, object] = {
        "type": "turn_context",
        "payload": {"turn_id": turn_id, "model": model, "effort": effort},
    }
    if timestamp is not None:
        row["timestamp"] = timestamp
    return row


def child_event(session_id: str) -> dict:
    return {
        "type": "event_msg",
        "payload": {
            "type": "sub_agent_activity",
            "agent_thread_id": session_id,
            "kind": "interrupted",
        },
    }


def load_helper_module():
    module_name = "pr_attribution_test_module"
    spec = importlib.util.spec_from_file_location(module_name, SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError("unable to load attribution helper")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(module_name, None)
    return module


class PrAttributionTests(unittest.TestCase):
    def run_helper(
        self,
        codex_home: Path,
        *arguments: str,
        session_id: str | None = ROOT,
    ) -> str:
        environment = os.environ.copy()
        if session_id is None:
            environment.pop("CODEX_THREAD_ID", None)
        else:
            environment["CODEX_THREAD_ID"] = session_id
        result = subprocess.run(
            [sys.executable, str(SCRIPT), "--codex-home", str(codex_home), *arguments],
            check=False,
            capture_output=True,
            text=True,
            env=environment,
            timeout=10,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, "")
        return result.stdout

    def test_recursive_family_majority_and_latest_context(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    meta(ROOT, ROOT),
                    turn("root-a", "max", timestamp="2026-08-11T12:00:00Z"),
                    turn("root-a", "xhigh"),
                    turn("root-b", "max"),
                    child_event(CHILD),
                ],
            )
            write_rollout(
                home,
                CHILD,
                [meta(CHILD, ROOT, parent_id=ROOT), turn("child-a", "xhigh"), child_event(GRANDCHILD)],
            )
            write_rollout(
                home,
                GRANDCHILD,
                [meta(GRANDCHILD, ROOT, parent_id=CHILD), turn("grandchild-a", "xhigh")],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Extra High"))

    def test_selected_child_chain_is_counted_without_parent_activity(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT), turn("root-a", "max")])
            write_rollout(
                home,
                CHILD,
                [
                    meta(CHILD, ROOT, parent_id=ROOT),
                    turn("child-a", "xhigh"),
                    turn("child-b", "xhigh"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                sentence("GPT-5.6 Sol Extra High"),
            )

    def test_selected_child_without_root_provenance_uses_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                CHILD,
                [meta(CHILD, None, source={"subagent": "review"}), turn("child-a", "max")],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                FALLBACK,
            )

    def test_selected_child_cannot_bypass_invalid_root_provenance(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [meta(ROOT, ROOT, source={"subagent": "review"}), turn("root-a", "max")],
            )
            write_rollout(
                home,
                CHILD,
                [
                    meta(CHILD, ROOT, parent_id=ROOT),
                    turn("child-a", "xhigh"),
                    turn("child-b", "xhigh"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                FALLBACK,
            )

    def test_legacy_id_only_root_is_counted(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    {"type": "session_meta", "payload": {"id": ROOT}},
                    turn("root-a", "max"),
                ],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Max"))

    def test_legacy_declared_subagent_without_parent_uses_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                CHILD,
                [
                    {
                        "type": "session_meta",
                        "payload": {"id": CHILD, "thread_source": "subagent"},
                    },
                    turn("child-a", "max"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                FALLBACK,
            )

    def test_unknown_legacy_prefix_does_not_conflict_with_child_provenance(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT, source="cli"), turn("root-a", "max")])
            write_rollout(
                home,
                CHILD,
                [
                    {"type": "session_meta", "payload": {"id": CHILD}},
                    meta(CHILD, ROOT, parent_id=ROOT),
                    turn("child-a", "xhigh"),
                    turn("child-b", "xhigh"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                sentence("GPT-5.6 Sol Extra High"),
            )

    def test_explicit_self_root_cannot_later_become_a_child(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT), turn("root-a", "max")])
            write_rollout(
                home,
                CHILD,
                [
                    meta(CHILD, CHILD),
                    meta(CHILD, ROOT, parent_id=ROOT),
                    turn("child-a", "xhigh"),
                    turn("child-b", "xhigh"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                FALLBACK,
            )

    def test_explicit_user_role_cannot_follow_a_parent_chain(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT), turn("root-a", "max")])
            write_rollout(
                home,
                CHILD,
                [
                    {
                        "type": "session_meta",
                        "payload": {
                            "id": CHILD,
                            "session_id": ROOT,
                            "parent_thread_id": ROOT,
                            "thread_source": "user",
                        },
                    },
                    turn("child-a", "xhigh"),
                    turn("child-b", "xhigh"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                FALLBACK,
            )

    def test_cli_source_can_be_refined_to_a_subagent_role(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT, source="cli"), turn("root-a", "max")])
            write_rollout(
                home,
                CHILD,
                [
                    {
                        "type": "session_meta",
                        "payload": {
                            "id": CHILD,
                            "session_id": ROOT,
                            "parent_thread_id": ROOT,
                            "source": "cli",
                        },
                    },
                    {
                        "type": "session_meta",
                        "payload": {
                            "id": CHILD,
                            "session_id": ROOT,
                            "parent_thread_id": ROOT,
                            "source": "cli",
                            "thread_source": "subagent",
                        },
                    },
                    turn("child-a", "xhigh"),
                    turn("child-b", "xhigh"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                sentence("GPT-5.6 Sol Extra High"),
            )

    def test_uuid_filename_without_root_metadata_uses_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [turn("root-a", "max")],
                add_owner_meta=False,
            )

            self.assertEqual(self.run_helper(home), FALLBACK)

    def test_conflicting_replayed_turn_uses_fallback(self) -> None:
        shared = "019ff116-ddd1-72f2-bff7-8a0d997c4b66"
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT), turn(shared, "max"), child_event(CHILD)])
            write_rollout(
                home,
                CHILD,
                [meta(CHILD, ROOT, parent_id=ROOT), meta(ROOT, ROOT), turn(shared, "xhigh")],
            )

            self.assertEqual(self.run_helper(home), FALLBACK)

    def test_repeated_lifecycle_prefix_deduplicates_replayed_turns(self) -> None:
        first = "019ff116-ddd1-72f2-bff7-8a0d997c4b66"
        second = "019ff117-ddd1-72f2-bff7-8a0d997c4b66"
        third = "019ff118-ddd1-72f2-bff7-8a0d997c4b66"
        latest = "019ff119-ddd1-72f2-bff7-8a0d997c4b66"
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    meta(ROOT, ROOT),
                    turn(first, "max"),
                    turn(second, "xhigh"),
                    turn(third, "xhigh"),
                    child_event(CHILD),
                ],
            )
            write_rollout(
                home,
                CHILD,
                [
                    meta(CHILD, ROOT, parent_id=ROOT),
                    meta(ROOT, ROOT),
                    turn(first, "max"),
                    turn(second, "xhigh"),
                    turn(third, "xhigh"),
                    meta(ROOT, ROOT),
                    meta(ROOT, ROOT),
                    turn(latest, "max"),
                ],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Max"))

    def test_later_lifecycle_prefix_deduplicates_partial_replay(self) -> None:
        child_first = "019ff116-ddd1-72f2-bff7-8a0d997c4b66"
        child_second = "019ff117-ddd1-72f2-bff7-8a0d997c4b66"
        root_latest = "019ff119-ddd1-72f2-bff7-8a0d997c4b66"
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT), turn(root_latest, "max"), child_event(CHILD)])
            write_rollout(
                home,
                CHILD,
                [
                    meta(CHILD, ROOT, parent_id=ROOT),
                    turn(child_first, "xhigh"),
                    turn(child_second, "xhigh"),
                    meta(ROOT, ROOT),
                    turn(root_latest, "max"),
                ],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Extra High"))

    def test_opaque_turn_ids_remain_lifecycle_scoped(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [meta(ROOT, ROOT), turn("root-a", "max"), child_event(CHILD)],
            )
            write_rollout(
                home,
                CHILD,
                [
                    meta(CHILD, ROOT, parent_id=ROOT),
                    turn("shared-opaque", "xhigh"),
                    child_event(GRANDCHILD),
                ],
            )
            write_rollout(
                home,
                GRANDCHILD,
                [meta(GRANDCHILD, ROOT, parent_id=CHILD), turn("shared-opaque", "xhigh")],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Extra High"))

    def test_ownerless_lifecycle_boundary_uses_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    meta(ROOT, ROOT),
                    {"type": "session_meta", "payload": {}},
                    turn("root-a", "max"),
                ],
            )

            self.assertEqual(self.run_helper(home), FALLBACK)

    def test_uuid_turn_aliases_are_deduplicated(self) -> None:
        latest = "019ff16a-1f1d-7eb1-a384-2ded9a4e86cb"
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    turn(latest, "xhigh"),
                    turn(latest.upper(), "xhigh"),
                    turn("019ff116-ddd1-72f2-bff7-8a0d997c4b66", "max"),
                    turn("019ff117-ddd1-72f2-bff7-8a0d997c4b66", "max"),
                ],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Max"))

    def test_latest_uuidv7_breaks_a_pair_mode_tie(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    turn("019ff116-ddd1-72f2-bff7-8a0d997c4b66", "xhigh"),
                    turn("019ff16a-1f1d-7eb1-a384-2ded9a4e86cb", "max"),
                ],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Max"))

    def test_ambiguous_turn_order_uses_fallback(self) -> None:
        cases = (
            ("turn-a", "turn-b"),
            (
                "019ff116-ddd1-72f2-bff7-8a0d997c4b66",
                "019ff116-ddd1-7fff-8fff-ffffffffffff",
            ),
        )
        for first, second in cases:
            with self.subTest(first=first), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, [turn(first, "xhigh"), turn(second, "max")])
                self.assertEqual(self.run_helper(home), FALLBACK)

    def test_desktop_effort_labels(self) -> None:
        labels = {
            "low": "Low",
            "medium": "Medium",
            "high": "High",
            "xhigh": "Extra High",
            "max": "Max",
            "ultra": "Ultra",
        }
        for effort, label in labels.items():
            with self.subTest(effort=effort), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, [turn("root-a", effort)])
                self.assertEqual(self.run_helper(home), sentence(f"GPT-5.6 Sol {label}"))

    def test_current_model_labels(self) -> None:
        models = {
            "gpt-5.5": "GPT-5.5",
            "gpt-5.6-sol": "GPT-5.6 Sol",
            "gpt-5.6-terra": "GPT-5.6 Terra",
        }
        for model, label in models.items():
            with self.subTest(model=model), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, [turn("root-a", "high", model=model)])
                self.assertEqual(self.run_helper(home), sentence(f"{label} High"))

    def test_unknown_or_missing_evidence_uses_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [turn("root-a", "ultra", model="future-model")])
            self.assertEqual(self.run_helper(home), FALLBACK)
            self.assertEqual(self.run_helper(home, session_id=UNRELATED), FALLBACK)
            self.assertEqual(self.run_helper(home, session_id=None), FALLBACK)

    def test_legacy_flat_archive_is_indexed_from_session_meta(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    {"type": "event_msg", "payload": {"type": "other"}},
                    {"type": "session_meta", "payload": {}},
                    {"type": "session_meta", "payload": {"session_id": ROOT}},
                    turn("root-a", "max"),
                ],
                relative_path=Path("archived_sessions", "rollout-legacy.jsonl"),
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Max"))

    def test_legacy_turn_before_lifecycle_owner_uses_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [turn("unknown-owner", "max"), meta(ROOT, ROOT)],
                relative_path=Path("archived_sessions", "rollout-legacy.jsonl"),
            )

            self.assertEqual(self.run_helper(home), FALLBACK)

    def test_active_tail_is_ignored_but_archived_tail_fails(self) -> None:
        for root_name, expected in (
            ("sessions", sentence("GPT-5.6 Sol Max")),
            ("archived_sessions", FALLBACK),
        ):
            with self.subTest(root_name=root_name), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                rollout = write_rollout(
                    home,
                    ROOT,
                    [turn("root-a", "max")],
                    relative_path=Path(root_name, f"rollout-{ROOT}.jsonl"),
                )
                with rollout.open("ab") as handle:
                    handle.write(b'{"type":"turn_context",')
                self.assertEqual(self.run_helper(home), expected)

    def test_legacy_root_source_shapes_are_accepted(self) -> None:
        sources = ("cli", "vscode")
        for source in sources:
            with self.subTest(source=source), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, [meta(ROOT, ROOT, source=source), turn("root-a", "max")])
                self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Max"))

    def test_modern_user_root_source_is_accepted(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    {
                        "type": "session_meta",
                        "payload": {
                            "id": ROOT,
                            "session_id": ROOT,
                            "source": "cli",
                            "thread_source": "user",
                        },
                    },
                    turn("root-a", "max"),
                ],
            )

            self.assertEqual(self.run_helper(home), sentence("GPT-5.6 Sol Max"))

    def test_explicit_subagent_source_cannot_claim_root(self) -> None:
        sources = (
            "subagent",
            {"subagent": "review"},
            {"subagent": {"kind": "guardian"}},
        )
        for source in sources:
            with self.subTest(source=source), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, [meta(ROOT, ROOT, source=source), turn("root-a", "max")])
                self.assertEqual(self.run_helper(home), FALLBACK)

    def test_thread_source_identifies_subagent_with_cli_source(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(home, ROOT, [meta(ROOT, ROOT, source="cli"), turn("root-a", "max")])
            write_rollout(
                home,
                CHILD,
                [
                    {
                        "type": "session_meta",
                        "payload": {
                            "id": CHILD,
                            "session_id": ROOT,
                            "parent_thread_id": ROOT,
                            "source": "cli",
                            "thread_source": "subagent",
                        },
                    },
                    turn("child-a", "xhigh"),
                    turn("child-b", "xhigh"),
                ],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", CHILD, session_id=UNRELATED),
                sentence("GPT-5.6 Sol Extra High"),
            )

    def test_replayed_lifecycle_claim_is_validated(self) -> None:
        invalid_sources = ({"subagent": "review"}, [])
        for source in invalid_sources:
            with self.subTest(source=source), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(
                    home,
                    ROOT,
                    [meta(ROOT, ROOT, source="cli"), turn("root-a", "max"), child_event(CHILD)],
                )
                write_rollout(
                    home,
                    CHILD,
                    [
                        meta(CHILD, ROOT, parent_id=ROOT),
                        meta(ROOT, ROOT, source=source),
                        turn("replayed-root", "max"),
                    ],
                )

                self.assertEqual(self.run_helper(home), FALLBACK)

    def test_replayed_lifecycle_parent_must_match_its_binding(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [meta(ROOT, ROOT), turn("root-a", "max"), child_event(CHILD)],
            )
            write_rollout(
                home,
                CHILD,
                [
                    meta(CHILD, ROOT, parent_id=ROOT),
                    turn("child-a", "xhigh"),
                ],
            )
            write_rollout(
                home,
                GRANDCHILD,
                [
                    meta(GRANDCHILD, ROOT, parent_id=CHILD),
                    {
                        "type": "session_meta",
                        "payload": {
                            "id": CHILD,
                            "session_id": ROOT,
                            "parent_thread_id": UNRELATED,
                            "thread_source": "subagent",
                        },
                    },
                    turn("replayed-child", "xhigh"),
                ],
            )
            write_rollout(
                home,
                UNRELATED,
                [meta(UNRELATED, UNRELATED), turn("unrelated-a", "ultra")],
            )

            self.assertEqual(
                self.run_helper(home, "--session-id", GRANDCHILD, session_id=UNRELATED),
                FALLBACK,
            )

    def test_invalid_or_conflicting_root_source_uses_fallback(self) -> None:
        cases = (
            [
                {"type": "session_meta", "payload": {"id": ROOT, "source": []}},
                turn("root-a", "max"),
            ],
            [
                {
                    "type": "session_meta",
                    "payload": {"id": ROOT, "thread_source": []},
                },
                turn("root-a", "max"),
            ],
            [
                {
                    "type": "session_meta",
                    "payload": {
                        "id": ROOT,
                        "session_id": ROOT,
                        "source": "subagent",
                    },
                },
                {
                    "type": "session_meta",
                    "payload": {
                        "id": ROOT,
                        "session_id": ROOT,
                        "source": "cli",
                        "thread_source": "user",
                    },
                },
                turn("root-a", "max"),
            ],
            [
                {
                    "type": "session_meta",
                    "payload": {
                        "id": ROOT,
                        "source": {"subagent": "review"},
                        "thread_source": "user",
                    },
                },
                turn("root-a", "max"),
            ],
        )
        for rows in cases:
            with self.subTest(rows=rows[:1]), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, rows)
                self.assertEqual(self.run_helper(home), FALLBACK)

    def test_invalid_provenance_uses_fallback(self) -> None:
        sources = (
            {"subagent": {"thread_spawn": []}},
            {"subagent": {"thread_spawn": {}}},
        )
        for source in sources:
            with self.subTest(source=source), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, [meta(ROOT, ROOT), child_event(CHILD)])
                write_rollout(home, CHILD, [meta(CHILD, ROOT, source=source), turn("child-a", "max")])
                self.assertEqual(self.run_helper(home), FALLBACK)

    def test_malformed_or_unsafe_evidence_uses_fallback(self) -> None:
        cases = (
            [{"type": [], "payload": {}}],
            [turn("x" * 1_025, "max")],
            [turn("root-a", "max"), child_event(CHILD)],
        )
        for rows in cases:
            with self.subTest(rows=rows[:1]), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(home, ROOT, rows)
                self.assertEqual(self.run_helper(home), FALLBACK)

        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            rollout = write_rollout(home, ROOT, [turn("root-a", "max")])
            with rollout.open("a", encoding="utf-8") as handle:
                handle.write("{malformed}\n")
            self.assertEqual(self.run_helper(home), FALLBACK)

    def test_ambiguous_or_nonprintable_filename_uses_fallback(self) -> None:
        filenames = (
            f"rollout-{ROOT}-{CHILD}.jsonl",
            f"rollout-\n-{ROOT}.jsonl",
        )
        for filename in filenames:
            with self.subTest(filename=filename), tempfile.TemporaryDirectory() as temporary_directory:
                home = Path(temporary_directory)
                write_rollout(
                    home,
                    ROOT,
                    [turn("root-a", "max")],
                    relative_path=Path("sessions", filename),
                )
                self.assertEqual(self.run_helper(home), FALLBACK)

    def test_conflicting_cross_file_copy_uses_fallback(self) -> None:
        shared = "019ff116-ddd1-72f2-bff7-8a0d997c4b66"
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [turn(shared, "max")],
                relative_path=Path("sessions", f"rollout-a-{ROOT}.jsonl"),
            )
            write_rollout(
                home,
                ROOT,
                [turn(shared, "max"), turn(shared, "xhigh")],
                relative_path=Path("sessions", f"rollout-b-{ROOT}.jsonl"),
            )
            self.assertEqual(self.run_helper(home), FALLBACK)

    def test_first_identifiable_lifecycle_must_match_filename(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            write_rollout(
                home,
                ROOT,
                [
                    {"type": "session_meta", "payload": {}},
                    meta(CHILD, CHILD),
                    turn("root-a", "max"),
                ],
            )
            self.assertEqual(self.run_helper(home), FALLBACK)

    @unittest.skipUnless(hasattr(os, "mkfifo"), "requires POSIX FIFO support")
    def test_fifo_uses_fallback_without_blocking(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            rollout = home / "sessions" / f"rollout-{ROOT}.jsonl"
            rollout.parent.mkdir(parents=True)
            os.mkfifo(rollout)
            descriptor = os.open(rollout, os.O_RDWR | os.O_NONBLOCK)
            try:
                os.write(descriptor, (json.dumps(turn("root-a", "max")) + "\n").encode())
                self.assertEqual(self.run_helper(home), FALLBACK)
            finally:
                os.close(descriptor)

    @unittest.skipUnless(hasattr(os, "symlink"), "requires symlink support")
    def test_symlink_uses_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            home = Path(temporary_directory)
            target = write_rollout(
                home,
                ROOT,
                [turn("root-a", "max")],
                relative_path=Path("target.jsonl"),
            )
            link = home / "sessions" / f"rollout-{ROOT}.jsonl"
            link.parent.mkdir(parents=True)
            link.symlink_to(target)
            self.assertEqual(self.run_helper(home), FALLBACK)

    def test_rollout_identity_allows_append_but_rejects_replacement(self) -> None:
        helper = load_helper_module()
        with tempfile.TemporaryDirectory() as temporary_directory:
            directory = Path(temporary_directory)
            rollout = directory / "rollout.jsonl"
            rollout.write_text("{}\n", encoding="utf-8")
            metadata = rollout.stat()
            identity = (metadata.st_dev, metadata.st_ino)

            with rollout.open("a", encoding="utf-8") as handle:
                handle.write("{}\n")
            with helper.open_rollout(rollout, identity) as handle:
                self.assertEqual(handle.readline(), b"{}\n")

            replacement = directory / "replacement.jsonl"
            replacement.write_text("{}\n", encoding="utf-8")
            os.replace(replacement, rollout)
            with self.assertRaises(helper.RolloutError):
                helper.open_rollout(rollout, identity)

    def test_skill_contract_routes_pr_note_to_helper(self) -> None:
        skill = (
            REPO_ROOT / "skills" / "codex-session-mining" / "SKILL.md"
        ).read_text(encoding="utf-8")
        self.assertIn(
            "derive the OpenAI Codex PR attribution note from a task family",
            skill,
        )
        self.assertIn("## PR Attribution", skill)
        self.assertIn(
            'python3 "$CODEX_HOME/skills/codex-session-mining/scripts/pr_attribution.py"',
            skill,
        )
        self.assertIn("GPT-5.6 Sol Ultra", skill)
        self.assertIn("immediately before merge", skill)


if __name__ == "__main__":
    unittest.main()
