"""Narrow dependency ports between orchestrator components."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class ProjectionStatePort(Protocol):
    def _append_gap(self, *args: Any, **kwargs: Any) -> str: ...

    def _assert_state_identity(self, *args: Any, **kwargs: Any) -> None: ...

    def _block(self, *args: Any, **kwargs: Any) -> None: ...

    def _now(self, *args: Any, **kwargs: Any) -> str: ...


class JobsProjectionPort(Protocol):
    def _execution_contract(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _policy_token(self, *args: Any, **kwargs: Any) -> str: ...

    def _restore_shard_manifest(self, *args: Any, **kwargs: Any) -> Any: ...

    def _version_token(self, *args: Any, **kwargs: Any) -> str: ...


class ReductionStatePort(Protocol):
    def _append_gap(self, *args: Any, **kwargs: Any) -> str: ...


class ReductionProjectionPort(Protocol):
    MIXED_MODEL_ERA: str
    UNKNOWN_MODEL_ERA: str

    def _collect_refs(self, *args: Any, **kwargs: Any) -> set[str]: ...

    def _episode_turn_payloads(self, *args: Any, **kwargs: Any) -> Any: ...

    def _is_completed_episode_review(self, *args: Any, **kwargs: Any) -> bool: ...

    def _is_external_ref(self, *args: Any, **kwargs: Any) -> bool: ...

    def _is_resolved_review(self, *args: Any, **kwargs: Any) -> bool: ...

    def _partial_can_continue(self, *args: Any, **kwargs: Any) -> bool: ...

    def _review_plan_result(self, *args: Any, **kwargs: Any) -> Any: ...

    def _review_task(self, *args: Any, **kwargs: Any) -> Any: ...

    def _safe_coverage_payload(self, *args: Any, **kwargs: Any) -> Any: ...

    def _shard_limits_from_state(self, *args: Any, **kwargs: Any) -> Any: ...

    def _tasks_for_stage(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...


class ReductionJobsPort(Protocol):
    def _agent_input_fits(self, *args: Any, **kwargs: Any) -> bool: ...

    def _create_agent_task(self, *args: Any, **kwargs: Any) -> Any: ...

    def _load_extracted_turns(self, *args: Any, **kwargs: Any) -> Any: ...

    def _stage_run_file(self, *args: Any, **kwargs: Any) -> None: ...


class HistoryProjectionPort(Protocol):
    MIXED_MODEL_ERA: str
    UNKNOWN_MODEL_ERA: str

    def _active_attempt(self, *args: Any, **kwargs: Any) -> Any: ...

    def _collect_refs(self, *args: Any, **kwargs: Any) -> set[str]: ...

    def _cursor_before(self, *args: Any, **kwargs: Any) -> Any: ...

    def _model_era(self, *args: Any, **kwargs: Any) -> str: ...

    def _policy_token(self, *args: Any, **kwargs: Any) -> str: ...

    def _restore_shard_manifest(self, *args: Any, **kwargs: Any) -> Any: ...

    def _retained_model_era_for_turn(self, *args: Any, **kwargs: Any) -> str: ...

    def _retained_model_era_for_turns(self, *args: Any, **kwargs: Any) -> str: ...

    def _signal_counts(self, *args: Any, **kwargs: Any) -> dict[str, int]: ...

    def _tasks_for_stage(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...


class HistoryReductionPort(Protocol):
    def _synthesis_validation_results(self, *args: Any, **kwargs: Any) -> Any: ...


class SourceStatePort(Protocol):
    def _append_gap(self, *args: Any, **kwargs: Any) -> str: ...

    def _assert_state_identity(self, *args: Any, **kwargs: Any) -> None: ...

    def _now(self, *args: Any, **kwargs: Any) -> str: ...

    def _require_retention_active_state(self, *args: Any, **kwargs: Any) -> None: ...

    def _require_stage(self, *args: Any, **kwargs: Any) -> None: ...

    def _validate_ref(self, *args: Any, **kwargs: Any) -> str: ...

    def ensure_retention_active(self, *args: Any, **kwargs: Any) -> None: ...

    def load_state(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...


class SourceProjectionPort(Protocol):
    def _active_attempt(self, *args: Any, **kwargs: Any) -> Any: ...

    def _all_cells(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...

    def _claim_is_expired(self, *args: Any, **kwargs: Any) -> bool: ...

    def _shard_limits_from_state(self, *args: Any, **kwargs: Any) -> Any: ...

    def _source_model_era(self, *args: Any, **kwargs: Any) -> str | None: ...

    def _status_view(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _task_for_active_job(self, *args: Any, **kwargs: Any) -> Any: ...

    def _validate_external_ref(self, *args: Any, **kwargs: Any) -> str: ...


class SourceJobsPort(Protocol):
    def _agent_envelope(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _materialize_agent_result_sink(self, *args: Any, **kwargs: Any) -> None: ...

    def _execution_manifest(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...


class SourceHistoryPort(Protocol):
    def _typed_agent_gap(self, *args: Any, **kwargs: Any) -> Any: ...

    def _validate_agent_result(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...


class LifecycleStatePort(Protocol):
    def _assert_state_identity(self, *args: Any, **kwargs: Any) -> None: ...

    def _block(self, *args: Any, **kwargs: Any) -> None: ...

    def _now(self, *args: Any, **kwargs: Any) -> str: ...

    def _require_stage(self, *args: Any, **kwargs: Any) -> None: ...

    def _retention_expired(self, *args: Any, **kwargs: Any) -> bool: ...

    def _transition(self, *args: Any, **kwargs: Any) -> None: ...

    def _validate_ref(self, *args: Any, **kwargs: Any) -> str: ...

    def load_state(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...


class LifecycleProjectionPort(Protocol):
    def _cursor_before(self, *args: Any, **kwargs: Any) -> Any: ...

    def _model_era(self, *args: Any, **kwargs: Any) -> str: ...

    def _partial_can_continue(self, *args: Any, **kwargs: Any) -> bool: ...

    def _policy_token(self, *args: Any, **kwargs: Any) -> str: ...

    def _status_view(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...


class LifecycleHistoryPort(Protocol):
    def _episode_head_projection(self, *args: Any, **kwargs: Any) -> Any: ...

    def _publication_durable_state(self, *args: Any, **kwargs: Any) -> Any: ...

    def retained_export_inputs(self, *args: Any, **kwargs: Any) -> Any: ...


class LifecycleSourcePort(Protocol):
    def _aggregate_source_segments(self, *args: Any, **kwargs: Any) -> Any: ...

    def _source_job_for_lease(self, *args: Any, **kwargs: Any) -> Any: ...

    def _transport_authorization(self, *args: Any, **kwargs: Any) -> Any: ...

    def _validate_authoritative_source_snapshot(
        self, *args: Any, **kwargs: Any
    ) -> None: ...


class SchedulerStatePort(Protocol):
    def _append_gap(self, *args: Any, **kwargs: Any) -> str: ...

    def _assert_state_identity(self, *args: Any, **kwargs: Any) -> None: ...

    def _block(self, *args: Any, **kwargs: Any) -> None: ...

    def _now(self, *args: Any, **kwargs: Any) -> str: ...

    def _require_retention_active_state(self, *args: Any, **kwargs: Any) -> None: ...

    def _require_stage(self, *args: Any, **kwargs: Any) -> None: ...

    def _retention_expired(self, *args: Any, **kwargs: Any) -> bool: ...

    def _transition(self, *args: Any, **kwargs: Any) -> None: ...

    def ensure_retention_active(self, *args: Any, **kwargs: Any) -> None: ...


class SchedulerProjectionPort(Protocol):
    def _all_cells(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...

    def _cursor_before(self, *args: Any, **kwargs: Any) -> Any: ...

    def _empty_synthesis_result(self, *args: Any, **kwargs: Any) -> Any: ...

    def _execution_contract(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _is_verified_no_activity(self, *args: Any, **kwargs: Any) -> bool: ...

    def _partial_can_continue(self, *args: Any, **kwargs: Any) -> bool: ...

    def _source_has_gaps(self, *args: Any, **kwargs: Any) -> bool: ...

    def _stage_has_gaps(self, *args: Any, **kwargs: Any) -> bool: ...

    def _stage_has_runnable_task(self, *args: Any, **kwargs: Any) -> bool: ...

    def _source_transport_output_path(self, *args: Any, **kwargs: Any) -> Path: ...

    def _status_view(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _tasks_for_stage(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...


class SchedulerJobsPort(Protocol):
    def _agent_envelope(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _execution_manifest(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _stage_run_file(self, *args: Any, **kwargs: Any) -> None: ...

    def _task_input_staging_scope(self, *args: Any, **kwargs: Any) -> Any: ...


class SchedulerReductionPort(Protocol):
    def _bind_episode_revisions(self, *args: Any, **kwargs: Any) -> Any: ...

    def _build_topic_inputs(self, *args: Any, **kwargs: Any) -> Any: ...

    def _construct_episode_revisions(self, *args: Any, **kwargs: Any) -> Any: ...

    def _freeze_catalog_and_materialize(self, *args: Any, **kwargs: Any) -> Any: ...

    def _record_unmaterialized_catalog_metrics(
        self, *args: Any, **kwargs: Any
    ) -> Any: ...

    def _refresh_review_plan(self, *args: Any, **kwargs: Any) -> Any: ...

    def _refresh_synthesis_hierarchy(self, *args: Any, **kwargs: Any) -> Any: ...

    def _refresh_topic_hierarchies(self, *args: Any, **kwargs: Any) -> Any: ...

    def _seed_synthesis_task(self, *args: Any, **kwargs: Any) -> Any: ...


class SchedulerHistoryPort(Protocol):
    def _build_retained_export(self, *args: Any, **kwargs: Any) -> Any: ...


class SchedulerSourcePort(Protocol):
    def _authorize_transport_receipt(self, *args: Any, **kwargs: Any) -> Any: ...

    def accept_source(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...


class SchedulerLifecyclePort(Protocol):
    def gc_expired_raw(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
